title: "Dialberth Ayala | Negocios & Tecnología"
description: "Bitácora sobre finanzas, desarrollo web, aprendizaje continuo y visión empresarial."
url: "https://Dialberth.github.io"
baseurl: "/blog"

# Usamos un tema nativo de GitHub que no requiere plugins para validar que todo conecte
theme: jekyll-theme-cayman